FROM python:3.11-slim

USER root
RUN apt-get update && apt-get install -y \
    default-jdk \
    curl \
    libpq-dev \
    gcc \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/default-java
ENV SPARK_HOME=/opt/spark
ENV AIRFLOW_HOME=/opt/airflow
ENV PATH="/home/airflow/.local/bin:${SPARK_HOME}/bin:${PATH}"

RUN useradd -ms /bin/bash airflow
RUN mkdir -p /opt/airflow/logs /opt/airflow/dags && \
    chown -R airflow:airflow /opt/airflow

USER airflow

RUN pip install --user \
    "apache-airflow==2.9.1" \
    apache-airflow-providers-apache-spark \
    psycopg2-binary